version: '3.4'

services:
  backend:
    image: agilizeit:backend
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    image: agilizeit:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile